[package]
name = "stream_xlsx"
version = "0.3.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
polars = "0.53.0"
polars-arrow = "0.53.0"
polars-buffer = "0.53.0"
quick-xml = "0.39"
zip = { version = "2", default-features = false, features = ["deflate"] }
flate2 = { version = "1", default-features = false, features = ["zlib-rs"] }
bytes = "1.11.1"
atoi_simd = "0.18.1"
fast-float = "0.2.0"
crossbeam-channel = "0.5"
